name: expense_tracker
description: An expense tracker app

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  syncfusion_flutter_charts: ^26.1.42
  shared_preferences: ^2.0.13
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  google_sign_in: ^6.0.2
  intl: ^0.19.0
  flutter_local_notifications: ^9.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
