// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1YRhS_xtq7hlbGZxWRrwKBO_Niix_2Zs',
    appId: '1:1000987664058:web:01b4b4fbf6402a69686c83',
    messagingSenderId: '1000987664058',
    projectId: 'expensetrackerapp-62e36',
    authDomain: 'expensetrackerapp-62e36.firebaseapp.com',
    storageBucket: 'expensetrackerapp-62e36.appspot.com',
    measurementId: 'G-8EGGQJ0QBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYFdSZJpxOCDJj7kvFrGH50nNGK9IBnQs',
    appId: '1:1000987664058:android:3c3eaea1d27ba77f686c83',
    messagingSenderId: '1000987664058',
    projectId: 'expensetrackerapp-62e36',
    storageBucket: 'expensetrackerapp-62e36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuValyU9_OL_AD96ZiEcHs7wK_C0a8ZnY',
    appId: '1:1000987664058:ios:c99f6cf5ca2b39fd686c83',
    messagingSenderId: '1000987664058',
    projectId: 'expensetrackerapp-62e36',
    storageBucket: 'expensetrackerapp-62e36.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuValyU9_OL_AD96ZiEcHs7wK_C0a8ZnY',
    appId: '1:1000987664058:ios:c99f6cf5ca2b39fd686c83',
    messagingSenderId: '1000987664058',
    projectId: 'expensetrackerapp-62e36',
    storageBucket: 'expensetrackerapp-62e36.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1YRhS_xtq7hlbGZxWRrwKBO_Niix_2Zs',
    appId: '1:1000987664058:web:606cc8443ec70523686c83',
    messagingSenderId: '1000987664058',
    projectId: 'expensetrackerapp-62e36',
    authDomain: 'expensetrackerapp-62e36.firebaseapp.com',
    storageBucket: 'expensetrackerapp-62e36.appspot.com',
    measurementId: 'G-Q86KQ6L7B7',
  );
}
